config/routes.rb
Salved::Application.routes.draw do
  
  resources :elaborations do
    resources :steps
  end

  resources :problem_events

  resources :problems do
    member do
      get 'answer'
    end
  end

end

app/models/elaboration.rb
class Elaboration < ActiveRecord::Base
  belongs_to :problem
  
  has_many :steps, :order => "index ASC"
  accepts_nested_attributes_for :steps
  
  
end
# == Schema Information
#
# Table name: elaborations
#
#  id                 :integer         not null, primary key
#  status             :string(255)
#  difficulty         :integer
#  note_to_self       :text
#  note_to_instructor :text
#  created_at         :datetime
#  updated_at         :datetime
#  problem_id         :integer
#

app/controllers/elaborations_controller.rb
class ElaborationsController < ApplicationController
  # GET /elaborations
  # GET /elaborations.json
  def index
    @elaborations = Elaboration.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elaborations }
    end
  end

  # GET /elaborations/1
  # GET /elaborations/1.json
  def show
    @elaboration = Elaboration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @elaboration }
    end
  end

  # GET /elaborations/new
  # GET /elaborations/new.json
  def new
    @elaboration = Elaboration.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @elaboration }
    end
  end

  # GET /elaborations/1/edit
  def edit
    @elaboration = Elaboration.find(params[:id])
    # debugger
  end

  # POST /elaborations
  # POST /elaborations.json
  def create
    @elaboration = Elaboration.new(params[:elaboration])

    respond_to do |format|
      if @elaboration.save
        format.html { redirect_to @elaboration, notice: 'Elaboration was successfully created.' }
        format.json { render json: @elaboration, status: :created, location: @elaboration }
      else
        format.html { render action: "new" }
        format.json { render json: @elaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elaborations/1
  # PUT /elaborations/1.json
  def update
    @elaboration = Elaboration.find(params[:id])

    # FIXME hack around Backbone storing nested models in 'modelname' instead of 'modelname_attributes'
    # REF https://github.com/documentcloud/backbone/issues/370
    # params[:elaboration][:steps_attributes] = params[:elaboration].delete(:steps)
    
    respond_to do |format|
      if @elaboration.update_attributes(params[:elaboration])
        format.html { redirect_to @elaboration, notice: 'Elaboration was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @elaboration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elaborations/1
  # DELETE /elaborations/1.json
  def destroy
    @elaboration = Elaboration.find(params[:id])
    @elaboration.destroy

    respond_to do |format|
      format.html { redirect_to elaborations_url }
      format.json { head :ok }
    end
  end
end

app/helpers/elaborations_helper.rb
module ElaborationsHelper
end

app/views/elaborations/_form.html.erb
<%= form_for(@elaboration) do |f| %>
  <h1><%= @elaboration.steps.length %></h1>

  <% if @elaboration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@elaboration.errors.count, "error") %> prohibited this elaboration from being saved:</h2>

      <ul>
      <% @elaboration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br />
    <%= f.number_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :note_to_self %><br />
    <%= f.text_area :note_to_self %>
  </div>
  <div class="field">
    <%= f.label :note_to_instructor %><br />
    <%= f.text_area :note_to_instructor %>
  </div>
  
  <%= f.fields_for :steps do |fs| %>
  <p>
    <%= fs.label :justification, "Justification" %> <%= fs.object.index %><br />
    <%= fs.text_area :justification, :rows => 3 %>  
  </p>  
  <% end %>    
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elaborations/edit.html.erb
<h1>Editing elaboration</h1>

<%= render 'form' %>

<%= link_to 'Show', @elaboration %> |
<%= link_to 'Back', elaborations_path %>

app/views/elaborations/index.html.erb
<div id="elaborations"></div>

<script type="text/javascript">
  $(function() {
    // Blog is the app name
    window.router = new Salved.Routers.ElaborationsRouter({elaborations: <%= @elaborations.to_json.html_safe -%>});
    Backbone.history.start();
  });
</script>

<h1>Listing elaborations</h1>

<table>
  <tr>
    <th>Status</th>
    <th>Difficulty</th>
    <th>Note to self</th>
    <th>Note to instructor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elaborations.each do |elaboration| %>
  <tr>
    <td><%= elaboration.status %></td>
    <td><%= elaboration.difficulty %></td>
    <td><%= elaboration.note_to_self %></td>
    <td><%= elaboration.note_to_instructor %></td>
    <td><%= link_to 'Show', elaboration %></td>
    <td><%= link_to 'Edit', edit_elaboration_path(elaboration) %></td>
    <td><%= link_to 'Destroy', elaboration, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Elaboration', new_elaboration_path %>

app/views/elaborations/new.html.erb
<h1>New elaboration</h1>

<%= render 'form' %>

<%= link_to 'Back', elaborations_path %>

app/views/elaborations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @elaboration.status %>
</p>

<p>
  <b>Difficulty:</b>
  <%= @elaboration.difficulty %>
</p>

<p>
  <b>Note to self:</b>
  <%= @elaboration.note_to_self %>
</p>

<p>
  <b>Note to instructor:</b>
  <%= @elaboration.note_to_instructor %>
</p>


<ol>  
  <% for step in @elaboration.steps %>  
  <li><%= step.justification %></li>  
  <% end %>  
</ol>  


<%= link_to 'Edit', edit_elaboration_path(@elaboration) %> |
<%= link_to 'Back', elaborations_path %>