config/routes.rb
Salved::Application.routes.draw do
  
  resources :elaborations do
    resources :steps
  end

  resources :problem_events

  resources :problems do
    member do
      get 'answer'
    end
  end

end

app/models/problem.rb
class Problem < ActiveRecord::Base
  has_many :problem_events
  has_many :elaborations
  
  validates_presence_of :label, :filesPath, :step_count
  
  
end
# == Schema Information
#
# Table name: problems
#
#  id           :integer         not null, primary key
#  label        :string(255)
#  filesPath    :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  step_count   :integer
#  explanations :text
#

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  # GET /problems
  # GET /problems.json
  def index
    @problems = Problem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problems }
    end
  end
  
  # GET /problems/1/answer
  def answer
    @problem = Problem.find(params[:id])
    # FIXME get the elaboration (or create it) for *current_user*
    @elaboration = Elaboration.find(2) || Elaboration.create

    respond_to do |format|
      format.html # answer.html.erb
    end
  end
  

  # GET /problems/1
  # GET /problems/1.json
  def show
    @problem = Problem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/new
  # GET /problems/new.json
  def new
    @problem = Problem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem }
    end
  end

  # GET /problems/1/edit
  def edit
    @problem = Problem.find(params[:id])
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(params[:problem])

    respond_to do |format|
      if @problem.save
        format.html { redirect_to @problem, notice: 'Problem was successfully created.' }
        format.json { render json: @problem, status: :created, location: @problem }
      else
        format.html { render action: "new" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problems/1
  # PUT /problems/1.json
  def update
    @problem = Problem.find(params[:id])

    respond_to do |format|
      if @problem.update_attributes(params[:problem])
        format.html { redirect_to @problem, notice: 'Problem was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    @problem = Problem.find(params[:id])
    @problem.destroy

    respond_to do |format|
      format.html { redirect_to problems_url }
      format.json { head :ok }
    end
  end
end

app/helpers/problems_helper.rb
module ProblemsHelper
  
  def explanations_for_problem problem
    # TODO only get latest from a user on a step. had it working but broke on Heroku's PostgreSQL
    ary = problem.problem_events.where(:name => 'explanation')
    
    ary.inject({}) { |hash, obj|
      step = obj['step']
      hash[step] = [] unless hash[step]
      hash[step] << obj['value']
      hash
    }

  end

end

app/views/problems/_form.html.erb
<%= form_for(@problem) do |f| %>
  <% if @problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
      <% @problem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :label %><br />
    <%= f.text_field :label %>
  </div>
  
  <p>(template with <tt>{{stepIndex}}</tt> like <i>https://dl.dropbox.com/s/ghum2hzpg5h6451/examN_question3/step-{{stepIndex}}.gif</i>)</p>
  <div class="field">
    <%= f.label :filesPath %><br />
    <%= f.text_field :filesPath %>
  </div>
  <div class="field">
    <%= f.label :step_count %><br />
    <%= f.number_field :step_count %>
  </div>
  <div class="field">
    <%= f.label :explanations %><br />
    <%= f.text_area :explanations %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problems/answer.html.erb
<script type="text/javascript" charset="utf-8">
$(function() {
  options = { student_solves: false, // FIXME pull try_solving from an attr of current_user
              problem: <%= @problem.to_json.html_safe -%>,
              elaboration: <%= @elaboration.to_json().html_safe -%>,
              steps: <%= @elaboration.steps.to_json().html_safe -%> }
  window.router = new Salved.Routers.AnswerRouter(options);
  Backbone.history.start();
});
</script>

<div id="prototype">
  
  <div id="problem">


    <div id="bookmark">
      <a href="#" id="problem_bookmark" class="star-off" title="Star to review later">review</a>
    </div>

    
    <img id="work_shown" src=""> <!-- set by Javascript -->
    
  </div>
  
  <div id="prompt" class="right-box">
    <p class="hovertip" title="Can you do it?">Try solving the problem at left on your paper.  <a class="hovertip-cue">[?]</a></p>
    <textarea name="justification" placeholder="Why is your work correct?"></textarea>
    
    <button id="work_check" class="advance_problem">Check my work</button>
    <button id="work_help" class="advance_problem">Get help</button>
  </div>
  
  <div id="work-check" class="right-box">
    <p>At left is an expert's work.<br>Is your work right?</p>

    <button class="record-check" id="same">Yes and similar.</button><br>
    <button class="record-check" id="different">Yes but different.</button><br>
    <button class="record-check" id="partly">Partly right.</button><br>
    <button class="record-check" id="not">Not at all.</button>
  </div>
  
  <div id="dialog" class="right-box">
    
    <div id="explanations">
      
      <div id="write_explanation" class="dialog_section">
        <div id="why">
          <p class="hovertip" title="Explaining to yourself helps you learn better and can help your classmates too when you share.">Why did the expert do this? <a class="hovertip-cue" >[?]</a></p>
          <textarea name="explanation"></textarea>
          <a href="#" id="paste_justification">paste earlier justification</a>
          <span id="privacy_choice"><input type="checkbox" name="private" id="private" value="check"><label for="private">don't share</label></span>
        </div>
        &nbsp;
        <div id="rate_own">
          <p class="hovertip" title="This helps you keep track of your explanations and improves the explanation pool.">How good is your explanation? <a class="hovertip-cue" >[?]</a></p>
          <button class="show_prior" id="poor">Poor</button>
          <button class="show_prior" id="good">Good</button>
          <button class="show_prior" id="very_good">Very good</button>
        </div>
      </div>
    
      <div id="read_explanations">
        <p id="prior_explanation">&lt;PRIOR EXPLANATION&gt;</p>
        <p class="guidance">Does this help you?
          <button id="thumbs_up"></button><button id="thumbs_down"></button>
        </p>
        <div>
          <button id="increment_explanation">Show another</button>
          <button id="revise_explanation">Revise mine</button>
          
        </div>    
      </div>
      
    </div>

    <div id="understanding" class="dialog_section">
      <p class="hovertip" title="This helps you keep track of your progress and improves the explanation pool.">Do you understand the uncovered work? <a class="hovertip-cue">[?]</a></p>
      <button id="understand_not_btn" class="advance_step">Not yet</button>
      <button id="understand_yes_btn" class="advance_step">Yes</button>
      <!-- <input type="checkbox" name="understand" id="understand"><label for="understand">I understand the expert's work.</label><br>
      <input type="checkbox" name="differently" id="differently"><label for="differently">I would do it differently.</label><br>
      <input type="checkbox" name="bookmark" id="bookmark"><label for="bookmark">Review this problem later.</label>
    </div>
    
    <div id="continue" class="dialog_section">
      <button id="step_understood_btn" class="advance_step">Continue</button> -->
    </div>
      
  </div>

  <div id="feedback" class="right-box">
    <p>Almost done…</p>
    
    <p>How hard was this problem?</p>
    <input type="radio" name="difficulty_9pt" value="1" id="difficulty_1"><label for="difficulty_1">1: extremely easy</label><br>
    <input type="radio" name="difficulty_9pt" value="2" id="difficulty_2"><label for="difficulty_2">2: very easy</label><br>
    <input type="radio" name="difficulty_9pt" value="3" id="difficulty_3"><label for="difficulty_3">3: easy</label><br>
    <input type="radio" name="difficulty_9pt" value="4" id="difficulty_4"><label for="difficulty_4">4: somewhat easy</label><br>
    <input type="radio" name="difficulty_9pt" value="5" id="difficulty_5"><label for="difficulty_5">5: neither easy nor difficult</label><br>
    <input type="radio" name="difficulty_9pt" value="6" id="difficulty_6"><label for="difficulty_6">6: somewhat difficult</label><br>
    <input type="radio" name="difficulty_9pt" value="7" id="difficulty_7"><label for="difficulty_7">7: difficult</label><br>
    <input type="radio" name="difficulty_9pt" value="8" id="difficulty_8"><label for="difficulty_8">8: very difficult</label><br>
    <input type="radio" name="difficulty_9pt" value="9" id="difficulty_9"><label for="difficulty_9">9: extremeley difficult</label><br>
    
    <textarea name="note_to_self" placeholder="Notes to yourself…"></textarea>
    
    <textarea name="note_to_instructor" placeholder="Notes to the instructor…"></textarea>
    
    <button id="difficulty_rated_btn" class="finish_problem">Finish</button>
    
  </div>

  <div id="summary" class="right-box">
    <p>All done.</p>
    
    <p>Your stats:</p>
    <div id="post_question_stats">
      <h5>Work matched</h5>
      <table>
        <tr><td>Step 1</td><td>Yes</td></tr>
        <tr><td>Step 2</td><td>Different</td></tr>
        <tr><td>Step 3</td><td>Partly</td></tr>
        <tr><td>Step 4</td><td>Yes</td></tr>
        <tr style="border-top: 1px solid black"><td>Overall</td><td>50% yes</td></tr>
      </table>
      
      <h5>Understood</h5>
      <table>
        <tr><td>Step 1</td><td>Yes</td></tr>
        <tr><td>Step 2</td><td>Not yet</td></tr>
        <tr><td>Step 3</td><td>Not yet</td></tr>
        <tr><td>Step 4</td><td>Yes</td></tr>
        <tr style="border-top: 1px solid black"><td>Overall</td><td>50% yes</td></tr>
      </table>
      
      <h5>Time spent on this problem</h5>
      <table>
        <tr><td>Step 1</td><td>3 minutes</td></tr>
        <tr><td>Step 2</td><td>1 minute</td></tr>
        <tr><td>Step 3</td><td>2 minutes</td></tr>
        <tr><td>Step 4</td><td>1 minute</td></tr>
        <tr style="border-top: 1px solid black"><td>Overall</td><td>7 minutes</td></tr>
      </table>
      
    </div>
    
    <button>Try another similar question.</button>
    <br>
    <%= link_to 'Back to list of problems', problems_path %>
  </div>
  
</div>

app/views/problems/edit.html.erb
<h1>Editing problem</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<h1>Salved problems</h1>

<div id="blurb">
  <p>This tool is designed to help you learn more in less time. Cognitive science in recent years has discovered that working through examples step-by-step and explaining lead to deeper and more robust learning.</p>

<p>Working through these problems will take some more time than simply reading the solutions but you will get much more out of the time. Simply reading solutions can actually be counter-productive to learning. That's why we made this tool, to make it easier to study in this more effective way.</p>

<p>To start, just click on a problem below. Try solving the problem shown. If you're done or want help, click the appropriate button. When prompted for an explanation, take the time to think and describe why. You'll learn the most by following the prompts and not simply clicking ahead.</p>
</div>

<table>
  <tr>
    <th>Problem (click to answer)</th>
    <th>Step count</th>
  </tr>

<% @problems.each do |problem| %>
  <tr>
    <td><%= link_to problem.label, answer_problem_path(problem) %></td>
    <td><%= problem.step_count %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New problem</h1>

<%= render 'form' %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Label:</b>
  <%= @problem.label %>
</p>

<p>
  <b>Filespath:</b>
  <%= @problem.filesPath %>
</p>

<p>
  <b>Applicable explanations:</b>
  <%= debug explanations_for_problem(@problem) %>
</p>



<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>