config/routes.rb
Salved::Application.routes.draw do
  
  resources :elaborations do
    resources :steps
  end

  resources :problem_events

  resources :problems do
    member do
      get 'answer'
    end
  end

end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :elaboration
end
# == Schema Information
#
# Table name: steps
#
#  id             :integer         not null, primary key
#  index          :integer
#  justification  :text
#  selfcheck      :string(255)
#  created_at     :datetime
#  updated_at     :datetime
#  understood     :boolean
#  elaboration_id :integer
#

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  # GET /elaboration/1/steps
  # GET /elaboration/1/steps.json
  def index
    @steps = Elaboration.find(params[:elaboration_id]).steps.order(:index)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @steps }
    end
  end

  # GET /elaboration/1/steps/1
  # GET /elaboration/1/steps/1.json
  def show
    @step = Elaboration.find(params[:elaboration_id]).steps.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @step }
    end
  end

  # GET /elaboration/1/steps/new
  # GET /elaboration/1/steps/new.json
  def new
    @step = Elaboration.find(params[:elaboration_id]).steps.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @step }
    end
  end

  # GET /elaboration/1/steps/1/edit
  def edit
    @step = Elaboration.find(params[:elaboration_id]).steps.find(params[:id])
  end

  # POST /elaboration/1/steps
  # POST /elaboration/1/steps.json
  def create
    @step = Elaboration.find(params[:elaboration_id]).steps.build(params[:step])

    respond_to do |format|
      if @step.save
        format.html { redirect_to [@step.elaboration, @step], notice: 'Step was successfully created.' }
        format.json { render json: @step, status: :created, location: @step }
      else
        format.html { render action: "new" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elaboration/1/steps/1
  # PUT /elaboration/1/steps/1.json
  def update
    @step = Elaboration.find(params[:elaboration_id]).steps.find(params[:id])

    respond_to do |format|
      if @step.update_attributes(params[:step])
        format.html { redirect_to [@step.elaboration, @step], notice: 'Step was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elaboration/1/steps/1
  # DELETE /elaboration/1/steps/1.json
  def destroy
    elaboration = Elaboration.find(params[:elaboration_id])
    @step = elaboration.steps.find(params[:id])
    @step.destroy

    respond_to do |format|
      format.html { redirect_to elaboration_steps_url(elaboration) }
      format.json { head :ok }
    end
  end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_form.html.erb
<%= form_for([@elaboration, @step], :url => elaboration_steps_path(@elaboration)) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %><br />
    <%= f.number_field :index %>
  </div>
  <div class="field">
    <%= f.label :justification %><br />
    <%= f.text_area :justification %>
  </div>
  <div class="field">
    <%= f.label :selfcheck %><br />
    <%= f.text_field :selfcheck %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', [@step.elaboration, @step] %> |
<%= link_to 'Back', elaboration_steps_path(@step.elaboration) %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <tr>
    <th>Index</th>
    <th>Justification</th>
    <th>Selfcheck</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @steps.each do |step| %>
  <tr>
    <td><%= step.index %></td>
    <td><%= step.justification %></td>
    <td><%= step.selfcheck %></td>
    <td><%= link_to 'Show', [step.elaboration, step] %></td>
    <td><%= link_to 'Edit', edit_elaboration_step_path(step.elaboration, step) %></td>
    <td><%= link_to 'Destroy', [step.elaboration, step], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Step', new_elaboration_step_path(@elaboration) %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', elaboration_steps_path(@elaboration) %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Index:</b>
  <%= @step.index %>
</p>

<p>
  <b>Justification:</b>
  <%= @step.justification %>
</p>

<p>
  <b>Selfcheck:</b>
  <%= @step.selfcheck %>
</p>


<%= link_to 'Edit', edit_elaboration_step_path(@step.elaboration, @step) %> |
<%= link_to 'Back', elaboration_steps_path(@step.elaboration) %>