config/routes.rb
Salved::Application.routes.draw do
  
  resources :elaborations do
    resources :steps
  end

  resources :problem_events

  resources :problems do
    member do
      get 'answer'
    end
  end

end

app/models/problem_event.rb
class ProblemEvent < ActiveRecord::Base
  belongs_to :problem
  
  validates_presence_of :problem_id, :step, :name
  
end
# == Schema Information
#
# Table name: problem_events
#
#  id         :integer         not null, primary key
#  problem_id :integer
#  step       :integer
#  name       :string(255)
#  value      :text
#  ip_address :string(255)
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/problem_events_controller.rb
class ProblemEventsController < ApplicationController
  # GET /problem_events
  # GET /problem_events.json
  def index
    @problem_events = ProblemEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @problem_events }
    end
  end

  # GET /problem_events/1
  # GET /problem_events/1.json
  def show
    @problem_event = ProblemEvent.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @problem_event }
    end
  end

  # GET /problem_events/new
  # GET /problem_events/new.json
  def new
    @problem_event = ProblemEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @problem_event }
    end
  end

  # GET /problem_events/1/edit
  def edit
    @problem_event = ProblemEvent.find(params[:id])
  end

  # POST /problem_events
  # POST /problem_events.json
  def create
    @problem_event = ProblemEvent.new(params[:problem_event])
    @problem_event.ip_address = request.remote_ip

    respond_to do |format|
      if @problem_event.save
        format.html { redirect_to @problem_event, notice: 'Problem event was successfully created.' }
        format.json { render json: @problem_event, status: :created, location: @problem_event }
      else
        format.html { render action: "new" }
        format.json { render json: @problem_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /problem_events/1
  # PUT /problem_events/1.json
  def update
    @problem_event = ProblemEvent.find(params[:id])

    respond_to do |format|
      if @problem_event.update_attributes(params[:problem_event])
        format.html { redirect_to @problem_event, notice: 'Problem event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @problem_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_events/1
  # DELETE /problem_events/1.json
  def destroy
    @problem_event = ProblemEvent.find(params[:id])
    @problem_event.destroy

    respond_to do |format|
      format.html { redirect_to problem_events_url }
      format.json { head :ok }
    end
  end
end

app/helpers/problem_events_helper.rb
module ProblemEventsHelper
end

app/views/problem_events/_form.html.erb
<%= form_for(@problem_event) do |f| %>
  <% if @problem_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem_event.errors.count, "error") %> prohibited this problem_event from being saved:</h2>

      <ul>
      <% @problem_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :problem_id %><br />
    <%= f.text_field :problem_id %>
  </div>
  <div class="field">
    <%= f.label :step %><br />
    <%= f.text_field :step %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_area :value %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br />
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problem_events/edit.html.erb
<h1>Editing problem_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem_event %> |
<%= link_to 'Back', problem_events_path %>

app/views/problem_events/index.html.erb
<h1>Listing problem_events</h1>

<table>
  <tr>
    <th>Problem</th>
    <th>Step</th>
    <th>Name</th>
    <th>Value</th>
    <th>IP Address</th>
    <th>Time</th>
    <th></th>
  </tr>

<% @problem_events.each do |problem_event| %>
  <tr>
    <td><%= problem_event.problem_id %></td>
    <td><%= problem_event.step %></td>
    <td><%= problem_event.name %></td>
    <td><%= problem_event.value %></td>
    <td><%= problem_event.ip_address %></td>
    <td><%= problem_event.created_at %></td>
    <td><%= link_to 'Show', problem_event %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Problem event', new_problem_event_path %>

app/views/problem_events/new.html.erb
<h1>New problem_event</h1>

<%= render 'form' %>

<%= link_to 'Back', problem_events_path %>

app/views/problem_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Problem:</b>
  <%= @problem_event.problem_id %>
</p>

<p>
  <b>Step:</b>
  <%= @problem_event.step %>
</p>

<p>
  <b>Name:</b>
  <%= @problem_event.name %>
</p>

<p>
  <b>Value:</b>
  <%= @problem_event.value %>
</p>

<p>
  <b>Ip address:</b>
  <%= @problem_event.ip_address %>
</p>


<%= link_to 'Edit', edit_problem_event_path(@problem_event) %> |
<%= link_to 'Back', problem_events_path %>